### ISSUE TITLE
Invalid regex causes Traffic Router to refuse DNS requests

### ISSUE THREAD

**Issue by elsloo** [Comcast/traffic_control#1587]
The following exception occurred when an invalid regex was specified on a delivery service. It was a HOST regex at index 0. The exception occurred in such a way that Traffic Router was refusing all queries, which in practice, means that it has no zone data.

Fix the issue and ensure that an invalid regex only affects the delivery service on which it was configured, and log a big nasty fatal message.

This issue is related to and should be fixed along with #514.

```
INFO  2016-07-06T17:21:35.219 [New I/O worker #19] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - Generating zone data
FATAL 2016-07-06T17:21:35.220 [New I/O worker #19] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - Caught fatal exception while generating zone data!
org.xbill.DNS.TextParseException: '.\.some-ds-regex\..': invalid empty label
        at org.xbill.DNS.Name.parseException(Name.java:172)
        at org.xbill.DNS.Name.<init>(Name.java:251)
        at org.xbill.DNS.Name.<init>(Name.java:288)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.newName(ZoneManager.java:572)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.populateZoneMap(ZoneManager.java:622)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:349)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.initZoneCache(ZoneManager.java:172)
        at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.<init>(ZoneManager.java:110)
        at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.<init>(TrafficRouter.java:104)
        at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouterManager.setCacheRegister(TrafficRouterManager.java:101)
```

**Comment by dneuman64** [comment]
do we want to put validation in TO to ensure the HOST regex at item 0 always matches the pattern of ` .*\.<sometext>\..*`?
