### ISSUE TITLE
Need some help to configure Delivery Service

### ISSUE THREAD

**Issue by evyncke** [Comcast/traffic_control#1698]
Trying for 2 days to configure Traffic Control :-O without any major success. It is in a lab, so, I am using RFC 1918 IPv4 addresses and all addresses are not reachable from the Internet ;-)

Thanks in advance for any assistance for a good definition of Delivery Service (or suggestions where to hunt for misconfiguration).

On the traffic router, I have the following log entries:
```
INFO  2016-08-11T15:51:28.483 [New I/O worker #1] com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler - Exit: processConfig
INFO  2016-08-11T15:51:28.484 [New I/O worker #1] com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater - updated /opt/traffic_router/db/cr-config.json
WARN  2016-08-11T15:51:33.587 [pool-9-thread-219] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - subdomain NOT found: 'edge.vynckeorg.cdn.omd.6cn.solutions.'
WARN  2016-08-11T15:51:33.602 [pool-9-thread-220] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - subdomain NOT found: 'edge.vynckeorg.cdn.omd.6cn.solutions.'
WARN  2016-08-11T15:51:35.429 [pool-9-thread-221] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - subdomain NOT found: 'ccr.6labciscocom.cdn.omd.6cn.solutions.'
WARN  2016-08-11T15:51:35.445 [pool-9-thread-222] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - subdomain NOT found: 'ccr.6labciscocom.cdn.omd.6cn.solutions.'
WARN  2016-08-11T15:51:38.497 [pool-9-thread-223] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - subdomain NOT found: 'tedge.vynckeorg.cdn.omd.6cn.solutions.'
INFO  2016-08-11T16:06:28.187 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler - Enter: processConfig

```

(also wondering where the _'ccr'_ and _'tedge'_ are coming from...)

Other error messages:
```
INFO  2016-08-11T16:06:28.203 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - Successfully deleted /opt/traffic_router/var/auto-zones
INFO  2016-08-11T16:06:28.203 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - Generating zone data
FATAL 2016-08-11T16:06:28.377 [New I/O worker #2] com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager - Caught fatal exception while generating zone data!
java.net.UnknownHostException: trouter: trouter: Nom ou service inconnu (== unknown name or service)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1475)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.fillZones(ZoneManager.java:365)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.fillZones(ZoneManager.java:360)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.generateZones(ZoneManager.java:348)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.initZoneCache(ZoneManager.java:174)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.ZoneManager.<init>(ZoneManager.java:107)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouter.<init>(TrafficRouter.java:87)
	at com.comcast.cdn.traffic_control.traffic_router.core.router.TrafficRouterManager.setCacheRegister(TrafficRouterManager.java:82)
	at com.comcast.cdn.traffic_control.traffic_router.core.config.ConfigHandler.processConfig(ConfigHandler.java:122)
	at com.comcast.cdn.traffic_control.traffic_router.core.monitor.TrafficMonitorWatcher$2.update(TrafficMonitorWatcher.java:115)
	at com.comcast.cdn.traffic_control.traffic_router.core.util.PeriodicResourceUpdater.updateDatabase(PeriodicResourceUpdater.java:188)

```
Here is the generated cr-config.json:

```
{
  "contentServers": {"tedge": {
    "port": "80",
    "cacheGroup": "Edge-Cache",
    "status": "REPORTED",
    "hashId": "tedge",
    "ip6": "2001:xxx::27/64",
    "locationId": "Edge-Cache",
    "type": "EDGE",
    "fqdn": "tedge.omd.6cn.solutions",
    "ip": "10.60.26.27",
    "hashCount": 999,
    "interfaceName": "eth1",
    "deliveryServices": {
      "6LAB": ["tedge.6labciscocom.cdn.omd.6cn.solutions"],
      "VYNCKE_ORG": ["edge.vynckeorg.cdn.omd.6cn.solutions"]
    },
    "profile": "EDGE1"
  }},
  "contentRouters": {"trouter": {
    "id": "trouter",
    "port": "80",
    "status": "ONLINE",
    "location": "Edge-Cache",
    "ip6": "2001:xxx::51/64",
    "api.port": "3333",
    "fqdn": "trouter.omd.6cn.solutions",
    "ip": "10.60.26.51",
    "profile": "CCR_CDN"
  }},
  "monitors": {"tmonitor": {
    "port": "80",
    "status": "ONLINE",
    "location": "Edge-Cache",
    "ip6": "2001:xxx::53/64",
    "fqdn": "tmonitor.omd.6cn.solutions",
    "ip": "10.60.26.53",
    "profile": "RASCAL_CDNTM"
  }},
  "deliveryServices": {
    "6LAB": {
      "dispersion": {
        "limit": 1,
        "shuffled": "true"
      },
      "coverageZoneOnly": "false",
      "matchsets": [{
        "protocol": "HTTP",
        "matchlist": [{
          "regex": ".*\\.6labciscocom\\..*",
          "match-type": "HOST"
        }]
      }],
      "regionalGeoBlocking": "false",
      "ttls": {
        "AAAA": "3600",
        "SOA": "86400",
        "A": "3600",
        "NS": "3600"
      },
      "missLocation": {
        "long": "-87.627778",
        "lat": "41.881944"
      },
      "soa": {
        "expire": "604800",
        "minimum": "30",
        "admin": "twelve_monkeys",
        "retry": "7200",
        "refresh": "28800"
      },
      "ttl": "3600",
      "ip6RoutingEnabled": "true"
    },
    "VYNCKE_ORG": {
      "bypassDestination": {"DNS": {"ttl": "30"}},
      "coverageZoneOnly": "false",
      "matchsets": [{
        "protocol": "DNS",
        "matchlist": [{
          "regex": ".*\\.vynckeorg\\..*",
          "match-type": "HOST"
        }]
      }],
      "ttls": {
        "AAAA": "30",
        "SOA": "86400",
        "A": "30",
        "NS": "3600"
      },
      "missLocation": {
        "long": "-87.627778",
        "lat": "41.881944"
      },
      "soa": {
        "expire": "604800",
        "minimum": "30",
        "admin": "twelve_monkeys",
        "retry": "7200",
        "refresh": "28800"
      },
      "ttl": "30",
      "maxDnsIpsForLocation": "0",
      "ip6RoutingEnabled": "true"
    }
  },
  "stats": {
    "tm_version": "Release_002.001(007)_Build_34",
    "CDN_name": "6cn_omd",
    "tm_user": "admin",
    "tm_path": "/tools/write_crconfig/6cn_omd",
    "date": 1470931487,
    "tm_host": "tops.omd"
  },
  "edgeLocations": {"Edge-Cache": {
    "longitude": 2.265943,
    "latitude": 48.831
  }},
  "config": {
    "geolocation.polling.url": "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz",
    "api.cache-control.max-age": "10",
    "geolocation.polling.interval": "86400000",
    "domain_name": "cdn.omd.6cn.solutions",
    "ttls": {
      "AAAA": "3600",
      "SOA": "86400",
      "A": "3600",
      "NS": "3600"
    },
    "soa": {
      "expire": "604800",
      "minimum": "86400",
      "admin": "twelve_monkeys",
      "retry": "7200",
      "refresh": "28800"
    },
    "coveragezone.polling.url": "https://www.vyncke.org/coverage-zones.json",
    "coveragezone.polling.interval": "3600000"
  }
}

```

**Comment by knutsel** [comment]
Hey Eric, I'm sorry but we're kind of swamped on issues, as you may have found by our lack of response... Is this still an issue for you? If so, you could you please post the question at https://groups.google.com/forum/#!forum/traffic_control ?

**Comment by evyncke** [comment]
Jan,

Making progress, step by step...

I am coming back to the group if I am stuck

-éric


From:  Jan van Doorn <notifications@github.com>
Reply-To:  Comcast/traffic_control
<reply+0045bd1f98e67dd47ead2170d38719fbfd7a124d6f3a49b192cf0000000113cdf41e9
2a169ce0a2c81bf@reply.github.com>
Date:  Friday 19 August 2016 at 00:09
To:  Comcast/traffic_control <traffic_control@noreply.github.com>
Cc:  Eric Vyncke <eric@vyncke.org>, Author <author@noreply.github.com>
Subject:  Re: [Comcast/traffic_control] Need some help to configure Delivery
Service (#1698)

**Comment by knutsel** [comment]
OK, feel free to ping us on the list...
