### ISSUE TITLE
TR throws an error on startup when trying to download Geo Database

### ISSUE THREAD

**Issue by dneuman64** [Comcast/traffic_control#1851]
If the Geo Database already exists and TR is restarted, the following error is thrown in the log:  

> 2016-09-15 15:50:29,693 [FATAL] traffic_router.core.loc.AbstractServiceUpdater: [GeolocationDatabaseUpdater] Caught exception while attempting to download: https://trafops.kabletown.net/MaxMind/auto/GeoIP2-City.mmdb.gz
> java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
> 	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:248)
> 	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:255)
> 	at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:409)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
> 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
> 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.downloadDatabase(AbstractServiceUpdater.java:349)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.updateDatabase(AbstractServiceUpdater.java:130)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater$1.run(AbstractServiceUpdater.java:85)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
> 	at java.security.Provider$Service.newInstance(Provider.java:1617)
> 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
> 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
> 	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
> 	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
> 	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
> 	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
> 	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
> 	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
> 	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
> 	at java.net.URL.openConnection(URL.java:972)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.downloadDatabase(AbstractServiceUpdater.java:343)
> 	... 3 more
> Caused by: java.security.UnrecoverableKeyException: Password must not be null
> 	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:124)
> 	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:55)
> 	at java.security.KeyStore.getKey(KeyStore.java:1023)
> 	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
> 	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
> 	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
> 	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.getDefaultKeyManager(SSLContextImpl.java:874)
> 	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:732)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at java.security.Provider$Service.newInstance(Provider.java:1595)
> 	... 15 more

**Comment by dneuman64** [comment]
This issue is happening with https urls only. http URLs seem to work fine.

**Comment by dneuman64** [comment]
Also, by looking at the stack trace, it looks like this is do to the keystore.  The stacktrace is saying that the password cannot be null.
