### ISSUE TITLE
Traffic Router Exception (1.1.6)

### ISSUE THREAD

**Issue by smalenfant** [Comcast/traffic_control#599]
Not sure where this came from...  Couldn't really find the "equivalent" access.log since the time has now changed from `DNS [02/Oct/2015:19:28:53.516 +0000]` to `1443814934.357`.

```
ERROR 2015-10-06T00:11:58.703 [pool-9-thread-222] com.comcast.cdn.traffic_control.traffic_router.core.dns.NameServer - 
java.lang.NullPointerException
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.NameServer.addAnswers(NameServer.java:80)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.NameServer.query(NameServer.java:69)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.AbstractProtocol.query(AbstractProtocol.java:120)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.UDP$UDPPacketHandler.run(UDP.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
ERROR 2015-10-06T00:11:58.707 [pool-9-thread-222] com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.UDP - 
java.lang.NullPointerException
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.DNSAccessEventBuilder.createQuery(DNSAccessEventBuilder.java:100)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.DNSAccessEventBuilder.createDnsMessageHeader(DNSAccessEventBuilder.java:51)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.DNSAccessEventBuilder.createEvent(DNSAccessEventBuilder.java:45)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.DNSAccessEventBuilder.create(DNSAccessEventBuilder.java:86)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.AbstractProtocol.query(AbstractProtocol.java:128)
	at com.comcast.cdn.traffic_control.traffic_router.core.dns.protocol.UDP$UDPPacketHandler.run(UDP.java:105)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by elsloo** [comment]
I took a look at the code in commit 780ceb7, which is what TR 1.1.6 was built from, and it appears that in both cases we have an invalid DNS request that appears to be causing the null pointer exception.  We should protect against the NPE, but the good news is that it doesn't appear to be something that would affect a valid query.

Specifically, the first exception is being caused by this:

```
	private void addAnswers(final Message request, final Message response, final InetAddress clientAddress, final DNSAccessRecord.Builder builder) {
		final Record question = request.getQuestion();
		final int qclass = question.getDClass();
```

...the last line is line 80, and is being caused because ```request.getQuestion()``` is returning null.

The section exception is caused by this:

```
    private static String createQuery(final Record query) {
        final String qname = query.getName().toString();
```

...the last line is line 100 from the exception, and is being caused by either ```query``` itself being null, or ```query.getName()``` returning null.

Also, for what it's worth, we have not seen either of these (or any) exceptions logged in production in the last week.
